### 측정소별로 데이터 가져오기
- https://www.airkorea.or.kr/web/stationInfo?pMENU_NO=93 측정소 정보

- 대안동
- 상대동(진주)
- 상봉동
- 정촌면

In [1]:
import urllib
from urllib.parse import urlencode, quote_plus
import requests
from bs4 import BeautifulSoup
import json
from pandas import json_normalize

In [2]:
ServiceKey = "/Vg1J8MmKzuTqcg1RFWfc3U7B6OLQGu28VZvd9EkkL7l0+IYsdB5Oe0eTm85cUMsNyjZVrFo7GC8fKNxLqKRDA=="
open_url = 'http://apis.data.go.kr/B552584/ArpltnStatsSvc/getMsrstnAcctoRDyrg'

def get_미세먼지(측정소명):
    queryParams = '?' + urlencode({quote_plus('serviceKey') : ServiceKey,
                                   quote_plus('returnType') : 'json',
                                   quote_plus('numOfRows') : '10',
                                   quote_plus('pageNo') : '1',                               
                                   quote_plus('inqBginDt') : '20211126',
                                   quote_plus('inqEndDt') : '20220228',
                                   quote_plus('msrstnName') : 측정소명 })
    open_url_get = open_url + queryParams
    res = requests.get(open_url_get)
    info = json.loads(res.content)
    res_df = json_normalize(info["response"]["body"]["items"])
    return res_df

In [11]:
대안동 = get_미세먼지("대안동")
상대동 = get_미세먼지("상대동(진주)")
상봉동 = get_미세먼지("상봉동")
정촌면 = get_미세먼지("정촌면")

In [12]:
대안동

       msurDt so2Value coValue msrstnName pm10Value no2Value o3Value pm25Value
0  2021-11-26    .0034      .3        대안동        25    .0165    .022        12
1  2021-11-27    .0035      .5        대안동        25    .0223    .013        15
2  2021-11-28    .0037      .5        대안동        19    .0228    .012        14
3  2021-11-29     .005      .7        대안동        28    .0316     .01        22
4  2021-11-30    .0037      .7        대안동        20    .0209    .012        19
5  2021-12-01     .003      .3        대안동        12    .0043    .028        10
6  2021-12-02    .0037      .5        대안동        15    .0207    .012         9
7  2021-12-03    .0035      .5        대안동        22     .012    .025        12
8  2021-12-04    .0046      .6        대안동        22    .0205    .017        12
9  2021-12-05    .0038      .6        대안동        23    .0199    .013        18